const assert=require('assert');
const Stories=require('../src/data/stories.js');
const Catalog=require('../src/data/assetCatalog.js');
const Anchors=require('../src/utils/characterAnchors.js');
const Validation=require('../src/utils/sceneValidation.js');
const Composition=require('../src/utils/sceneComposition.js');
const fs=require('fs');const path=require('path');
let passed=0,failed=0;function test(name,fn){try{fn();passed++;console.log('PASS  '+name);}catch(e){failed++;console.log('FAIL  '+name+'\n      '+e.message);}}
function basic(layers){return{environment:'forest',layers:layers};}
const boy=(x=40,flipX=false)=>({id:'boy',assetId:'characterKidMale',pose:'hold',role:'actor',x:x,y:84,scale:1,flipX,z:3});
const phone=(scale=.16)=>({id:'phone',assetId:'objectPhone',role:'heldProp',scale,attach:{parent:'boy',anchor:'rightHand',offsetX:0,offsetY:0},z:4});
test('valid parent resolves and right-hand attachment follows actor',()=>{const a=Composition.resolveScene(basic([boy(30),phone()]),{width:400,height:286},Catalog);const b=Composition.resolveScene(basic([boy(50),phone()]),{width:400,height:286},Catalog);assert.strictEqual(a.findings.filter(f=>f.severity==='error').length,0);assert.ok(Math.abs((b.byId.phone.x-a.byId.phone.x)-20)<.01);});
test('missing attachment parent is rejected',()=>{const r=Composition.resolveScene(basic([phone()]),{width:400,height:286},Catalog);assert.ok(r.findings.some(f=>f.code==='MISSING_ATTACHMENT_PARENT'));});
test('worn backpack follows back anchor',()=>{const scene=basic([boy(),{id:'bag',assetId:'objectBackpack',role:'wornProp',scale:.48,attach:{parent:'boy',anchor:'back'},z:2}]);const r=Composition.resolveScene(scene,{width:400,height:286},Catalog);assert.ok(Math.abs(r.byId.bag.x-r.byId.boy.anchorPoints.back.x/4)<.01);});
test('known anchors resolve and unsupported anchors warn',()=>{assert.ok(Anchors.resolve('hold','rightHand',false));const r=Composition.resolveScene(basic([boy(),Object.assign(phone(),{attach:{parent:'boy',anchor:'elbow'}})]),{width:400,height:286},Catalog);assert.ok(r.findings.some(f=>f.code==='UNSUPPORTED_ANCHOR'));});
test('flipX mirrors the hand anchor',()=>{const a=Anchors.resolve('show','rightHand',false),b=Anchors.resolve('show','rightHand',true);assert.strictEqual(a.x,1-b.x);});
test('normal phone accepted and oversized phone flagged',()=>{const ok=Composition.resolveScene(basic([boy(),phone(.16)]),{width:400,height:286},Catalog);const bad=Composition.resolveScene(basic([boy(),phone(.6)]),{width:400,height:286},Catalog);assert.ok(!ok.findings.some(f=>f.code==='CRITICAL_PROP_OVERSIZED'));assert.ok(bad.findings.some(f=>f.code==='CRITICAL_PROP_OVERSIZED'));});
test('book covering face is flagged and chest book is accepted',()=>{const face={id:'book',assetId:'objectBookOpen',role:'heldProp',scale:.35,attach:{parent:'boy',anchor:'bothHands',offsetY:-11},z:4};const ok=Object.assign({},face,{scale:.21,attach:{parent:'boy',anchor:'bothHands',offsetY:0}});assert.ok(Composition.resolveScene(basic([boy(),face]),{width:400,height:286},Catalog).findings.some(f=>f.code==='PROP_OVERLAPS_FACE'));assert.ok(!Composition.resolveScene(basic([boy(),ok]),{width:400,height:286},Catalog).findings.some(f=>f.code==='PROP_OVERLAPS_FACE'));});
test('duplicate IDs, missing assets and illegal semantics are detected',()=>{const layers=[boy(),Object.assign(phone(),{id:'boy'}),{id:'bad',assetId:'missing',role:'placedProp',x:10,y:10,scale:1,z:2,attach:{parent:'boy',anchor:'rightHand'}}];const r=Composition.resolveScene(basic(layers),{width:400,height:286},Catalog);['DUPLICATE_LAYER_ID','UNKNOWN_ASSET','ILLEGAL_ATTACHMENT_ROLE'].forEach(code=>assert.ok(r.findings.some(f=>f.code===code),code));});
test('continuity detects unexplained scale changes',()=>{const story={id:'x',panels:[{id:'a',scene:{layers:[{id:'p',continuityKey:'p',scale:.2}]}},{id:'b',scene:{layers:[{id:'p',continuityKey:'p',scale:.3}]}}]};assert.ok(Validation.validateContinuity(story).some(f=>f.code==='CONTINUITY_SCALE_CHANGE'));});
test('responsive scaling preserves relative attachment positions',()=>{const s=basic([boy(),phone()]),a=Composition.resolveScene(s,{width:400,height:286},Catalog),b=Composition.resolveScene(s,{width:800,height:572},Catalog);assert.ok(Math.abs(b.byId.phone.boundsPx.left/a.byId.phone.boundsPx.left-2)<.001);});
test('z-order is deterministic',()=>{const r=Composition.resolveScene(basic([phone(),boy()]),{width:400,height:286},Catalog);for(let i=1;i<r.layers.length;i++)assert.ok(r.layers[i-1].z<=r.layers[i].z);});
test('pencil catalog ratio matches its real PNG dimensions',()=>{const asset=Catalog.objectPencil;const file=path.join(__dirname,'..',asset.path);const bytes=fs.readFileSync(file);const width=bytes.readUInt32BE(16),height=bytes.readUInt32BE(20);assert.strictEqual(width,42);assert.strictEqual(height,74);assert.ok(Math.abs(asset.aspectRatio-width/height)<.0001);});
test('all 20 canonical frames have zero validation findings at desktop and mobile sizes',()=>{let count=0;Object.values(Stories).forEach(story=>{assert.strictEqual(Validation.validateContinuity(story).length,0);story.panels.forEach(panel=>{count++;[{width:340,height:243},{width:300,height:225}].forEach(frame=>{const r=Composition.resolveScene(panel.scene,frame,Catalog,{storyId:story.id,panelId:panel.id});assert.deepStrictEqual(r.findings,[],panel.id+': '+r.findings.map(f=>f.code).join(','));});});});assert.strictEqual(count,20);});
console.log(`\n${passed} passed, ${failed} failed`);process.exit(failed?1:0);
