(function () {
  const composition=()=>window.TenseTales.utils.sceneComposition;
  function overlay(frame,resolved){
    resolved.layers.forEach((layer)=>{
      if(layer.boundsPx){const box=document.createElement('i');box.className='audit-overlay audit-bounds';box.style.cssText=`left:${layer.boundsPx.left/resolved.frame.width*100}%;top:${layer.boundsPx.top/resolved.frame.height*100}%;width:${layer.boundsPx.width/resolved.frame.width*100}%;height:${layer.boundsPx.height/resolved.frame.height*100}%`;frame.appendChild(box);}
      if(layer.role==='actor'){
        Object.entries(layer.anchorPoints).forEach(([name,p])=>{const dot=document.createElement('i');dot.className='audit-overlay audit-anchor';dot.title=name;dot.style.cssText=`left:${p.x/resolved.frame.width*100}%;top:${p.y/resolved.frame.height*100}%`;frame.appendChild(dot);});
        Object.values(layer.interactionZones).forEach((z)=>{const zone=document.createElement('i');zone.className='audit-overlay audit-zone';zone.style.cssText=`left:${(z.x-z.radius)/resolved.frame.width*100}%;top:${(z.y-z.radius)/resolved.frame.height*100}%;width:${z.radius*2/resolved.frame.width*100}%;height:${z.radius*2/resolved.frame.height*100}%`;frame.appendChild(zone);});
        const f=layer.faceZone,face=document.createElement('i');face.className='audit-overlay audit-face';face.style.cssText=`left:${f.left/resolved.frame.width*100}%;top:${f.top/resolved.frame.height*100}%;width:${f.width/resolved.frame.width*100}%;height:${f.height/resolved.frame.height*100}%`;frame.appendChild(face);
      }
    });
  }
  function preview(story,panel,kind,width,height){const wrap=document.createElement('div');wrap.className='audit-preview';const label=document.createElement('small');label.textContent=kind;const frame=document.createElement('div');frame.className='audit-frame '+(kind==='Mobile card'?'is-mobile':'');const resolved=composition().renderDom(frame,panel.scene,window.TenseTales.data.assetCatalog,{storyId:story.id,panelId:panel.id,frameBounds:{width:width,height:height}});overlay(frame,resolved);wrap.append(label,frame);return{wrap,resolved};}
  function card(story,panel){const article=document.createElement('article');article.className='audit-card';const head=document.createElement('header');head.className='audit-card-heading';head.innerHTML=`<div><strong>Level ${story.level} · Panel ${panel.order}</strong><h2>${story.title}</h2><p>${panel.actionLabel}</p></div><span>${panel.scene.environment}</span>`;const previews=document.createElement('div');previews.className='audit-previews';const desktop=preview(story,panel,'Desktop card',340,243),mobile=preview(story,panel,'Mobile card',300,225);previews.append(desktop.wrap,mobile.wrap);const findings=desktop.resolved.findings;const result=document.createElement('div');result.className='audit-result '+(findings.length?'has-findings':'is-valid');result.innerHTML=findings.length?findings.map(f=>`<p><strong>${f.severity.toUpperCase()} · ${f.code}</strong> ${f.message}</p>`).join(''):'<p><strong>PASS</strong> No scene validation findings.</p>';article.append(head,previews,result);return article;}
  function open(){document.querySelectorAll('body > main, #game-root, #story-order-shell').forEach(el=>{el.hidden=true;});const shell=document.getElementById('scene-audit-shell'),grid=document.getElementById('scene-audit-grid');shell.hidden=false;grid.textContent='';Object.values(window.TenseTales.data.stories).sort((a,b)=>a.level-b.level).forEach(story=>{const group=document.createElement('section');group.className='audit-story-group';const title=document.createElement('h2');title.textContent=`Level ${story.level} — ${story.title}`;const cards=document.createElement('div');cards.className='audit-story-cards';story.panels.forEach(panel=>cards.appendChild(card(story,panel)));group.append(title,cards);grid.appendChild(group);});document.querySelectorAll('[data-overlay]').forEach(input=>input.addEventListener('change',()=>shell.classList.toggle('show-'+input.dataset.overlay,input.checked)));}
  window.TenseTales.gameplay.openSceneAudit=open;
})();
